name-template: v$NEXT_MINOR_VERSION
sort-direction: ascending
categories:
  - title: '🚀 Features'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: '🐛 Bugfixes'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: '🧰 Chore'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
autolabeler:
  - label: 'kind/ci'
    title:
      - '/^ci.+/$'
    branch:
      - '/^ci\/.+/$'
  - label: 'kind/feature'
    title:
      - '/^feat.+/$'
    branch:
      - '/^feat\/.+/$'
  - label: 'kind/fix'
    title:
      - '/^fix.+/$'
    branch:
      - '/^fix\/.+/$'
  - label: 'kind/chore'
    title:
      - '/^chore.+/$'
    branch:
      - '/^chore\/.+/$'
  - label: 'kind/refactor'
    title:
      - '/^refactor.+/$'
    branch:
      - '/^refactor\/.+/$'
template: |
  # v$NEXT_MINOR_VERSION

  TODO: description

  ## Major changes

  TODO: list major changes

  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
  
  ----
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
